# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sensors/v1/imu.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'proto/sensors/v1/imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/sensors/v1/imu.proto\x12\nsensors.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x88\x02\n\tImuSample\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\r\x12-\n\x13linear_acceleration\x18\x04 \x01(\x0b\x32\x10.sensors.v1.Vec3\x12*\n\x10\x61ngular_velocity\x18\x05 \x01(\x0b\x32\x10.sensors.v1.Vec3\x12\x1f\n\x17\x61\x63\x63\x65leration_covariance\x18\x06 \x03(\x01\x12\x16\n\x0e\x63\x61libration_id\x18\x07 \x01(\t\x12\x18\n\x10source_device_id\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sensors.v1.imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEC3']._serialized_start=75
  _globals['_VEC3']._serialized_end=114
  _globals['_IMUSAMPLE']._serialized_start=117
  _globals['_IMUSAMPLE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
